// Unit tests for the iReal Pro import harmony pipeline:
//   src/irealParse.js   — extract, unscramble, field-split, tokenize
//   src/irealChord.js   — chord/key parsing, Roman/Letter rendering
//   src/harmonyModel.js — Song / ParsedPlaylist assembly
//
// These use a SMALL embedded sample only — a hand-crafted irealb:// HTML
// string whose scrambled bodies were generated by applying the (verified
// involutive) obfusc50 block transform to a known plaintext. We do NOT
// read the local "Jazz 1460.html" reference file here; that is exercised
// by the local (gitignored) validation script instead.
//
// Pure modules — no DOM, no esm.sh — so this runs under `node --test`.

import { test } from "node:test";
import assert from "node:assert/strict";

import {
  extractIrealPayload,
  unscramble,
  splitPlaylist,
  splitSong,
  tokenizeBody,
} from "../src/irealParse.js";
import {
  parseKey,
  parseChord,
  splitChordSymbol,
  rootToDegree,
  chordToRoman,
  chordToLetter,
  normaliseQuality,
} from "../src/irealChord.js";
import {
  parsePlaylistHtml,
  parsePlaylistPayload,
  buildSong,
} from "../src/harmonyModel.js";

// --- Embedded sample -------------------------------------------------
// Song 1 ("Test Tune", key C, 4/4): body plaintext was
//   "*A{T44C^7 |A-7 |D-7 |G7 }N1Z*B[F^7 |E7 |Eb7 |D7 |G^7XyQ]Z"
// then scrambled (so the test really exercises unscramble).
// Song 2 ("Minor Waltz", key A-, 3/4): plaintext
//   "T34A-7 |D7 |G^7 |C^7 |F^7 |Bh7 |E7b9 |A-7XyQZ"  (< 50 chars, unscrambled = itself)
const SAMPLE_HTML =
  '<a href="irealb://Test%20Tune%3DTester%20X%3DMedium%20Swing%3DC%3D1r34LbKcu7G%7C%207D4C%5E7%20%7C%207E%7C%207%5EF%5BB*Z1%7DN%207G%7C%207-D%7C%207-A%7CEb7%20%7C4T%7BA*%5E7XyQ%5DZ%3D%3D0%3D0%3D%3D%3DMinor%20Waltz%3DTester%20Y%3DJazz%20Waltz%3DA-%3D1r34LbKcu7T34A-7%20%7CD7%20%7CG%5E7%20%7CC%5E7%20%7CF%5E7%20%7CBh7%20%7CE7b9%20%7CA-7XyQZ%3D%3D0%3D0%3D%3D%3DMy%20Test%20List">x</a>';

const SONG1_BODY =
  "*A{T44C^7 |A-7 |D-7 |G7 }N1Z*B[F^7 |E7 |Eb7 |D7 |G^7XyQ]Z";

// --- unscramble ------------------------------------------------------

test("unscramble: leaves a <50-char remainder untouched", () => {
  assert.equal(unscramble("ABCDE"), "ABCDE");
  assert.equal(unscramble("T34A-7 |D7 "), "T34A-7 |D7 ");
});

test("unscramble: de-scrambles a real (>50 char) scrambled body", () => {
  const scrambled = "G| 7D4C^7 | 7E| 7^F[B*Z1}N 7G| 7-D| 7-A|Eb7 |4T{A*^7XyQ]Z";
  assert.equal(unscramble(scrambled), SONG1_BODY);
});

// --- field parsing ---------------------------------------------------

test("extractIrealPayload: pulls and decodes the irealb URL", () => {
  const payload = extractIrealPayload(SAMPLE_HTML);
  assert.ok(payload);
  assert.ok(payload.startsWith("Test Tune="));
  assert.ok(payload.endsWith("My Test List"));
});

test("splitPlaylist: separates songs from trailing playlist name", () => {
  const payload = extractIrealPayload(SAMPLE_HTML);
  const { name, songs } = splitPlaylist(payload);
  assert.equal(name, "My Test List");
  assert.equal(songs.length, 2);
  assert.equal(songs[0].title, "Test Tune");
  assert.equal(songs[1].title, "Minor Waltz");
});

test("splitSong: maps fields positionally and de-scrambles the body", () => {
  const chunk =
    "Test Tune=Tester X=Medium Swing=C=1r34LbKcu7T44C^7 |A-7 Z==0=0";
  const raw = splitSong(chunk);
  assert.equal(raw.title, "Test Tune");
  assert.equal(raw.composer, "Tester X");
  assert.equal(raw.style, "Medium Swing");
  assert.equal(raw.key, "C");
  assert.equal(raw.body, "T44C^7 |A-7 Z"); // prefix stripped, short = as-is
});

// --- key parsing -----------------------------------------------------

test("parseKey: major and minor, with accidentals", () => {
  assert.deepEqual(parseKey("C"), { tonicPitchClass: 0, mode: "major" });
  assert.deepEqual(parseKey("F"), { tonicPitchClass: 5, mode: "major" });
  assert.deepEqual(parseKey("Bb"), { tonicPitchClass: 10, mode: "major" });
  assert.deepEqual(parseKey("A-"), { tonicPitchClass: 9, mode: "minor" });
  assert.deepEqual(parseKey("C#-"), { tonicPitchClass: 1, mode: "minor" });
  assert.equal(parseKey(""), null);
  assert.equal(parseKey("H"), null);
});

// --- chord-shorthand parsing ----------------------------------------

test("splitChordSymbol: root, accidental, quality, slash bass", () => {
  assert.deepEqual(splitChordSymbol("G7"), {
    letter: "G", acc: "", quality: "7", bassLetter: null, bassAcc: "",
  });
  assert.deepEqual(splitChordSymbol("Bb^7"), {
    letter: "B", acc: "b", quality: "^7", bassLetter: null, bassAcc: "",
  });
  assert.deepEqual(splitChordSymbol("A-7/E"), {
    letter: "A", acc: "", quality: "-7", bassLetter: "E", bassAcc: "",
  });
  assert.deepEqual(splitChordSymbol("Dh7"), {
    letter: "D", acc: "", quality: "h7", bassLetter: null, bassAcc: "",
  });
});

test("normaliseQuality: strips size hints", () => {
  assert.equal(normaliseQuality("^7"), "^7");
  assert.equal(normaliseQuality("-7"), "-7");
  assert.equal(normaliseQuality(""), "");
});

// --- absolute -> degree (Roman) conversion --------------------------

test("rootToDegree: diatonic and chromatic roots in C major", () => {
  const C = parseKey("C");
  assert.deepEqual(rootToDegree("C", "", C), { degree: 1, accidental: "" });
  assert.deepEqual(rootToDegree("D", "", C), { degree: 2, accidental: "" });
  assert.deepEqual(rootToDegree("B", "b", C), { degree: 7, accidental: "b" });
  assert.deepEqual(rootToDegree("A", "b", C), { degree: 6, accidental: "b" });
  assert.deepEqual(rootToDegree("E", "", C), { degree: 3, accidental: "" });
});

test("rootToDegree: degrees relative to a minor key", () => {
  const Cm = parseKey("C-");
  assert.deepEqual(rootToDegree("C", "", Cm), { degree: 1, accidental: "" });
  assert.deepEqual(rootToDegree("E", "b", Cm), { degree: 3, accidental: "" }); // b3 is diatonic in minor
  assert.deepEqual(rootToDegree("D", "b", Cm), { degree: 2, accidental: "b" });
});

// --- chordToRoman / chordToLetter -----------------------------------

test("chordToRoman: common qualities in C major", () => {
  const C = parseKey("C");
  const roman = (s) => chordToRoman(parseChord(s, C));
  assert.equal(roman("C^7"), "Imaj7");
  assert.equal(roman("D-7"), "ii7");
  assert.equal(roman("G7"), "V7");
  assert.equal(roman("A-7"), "vi7");
  assert.equal(roman("Bb7"), "bVII7");
  assert.equal(roman("Dh7"), "iiø7");
  assert.equal(roman("C^7/E"), "Imaj7/III");
});

test("chordToLetter: correct enharmonic spelling in flat/sharp keys", () => {
  const C = parseKey("C");
  const letC = (s) => chordToLetter(parseChord(s, C), C);
  assert.equal(letC("C^7"), "Cmaj7");
  assert.equal(letC("A-7"), "Am7");
  assert.equal(letC("G7"), "G7");
  assert.equal(letC("Bb7"), "Bb7"); // not A#7
  assert.equal(letC("Ab7"), "Ab7"); // not G#7

  const Cm = parseKey("C-");
  const letCm = (s) => chordToLetter(parseChord(s, Cm), Cm);
  assert.equal(letCm("Eb-7"), "Ebm7"); // not D#m7
  assert.equal(letCm("Dh7"), "Dm7b5");
  assert.equal(letCm("G7b9"), "G7b9");
});

test("chordToLetter: 26-2 Coltrane changes (key F)", () => {
  const F = parseKey("F");
  const let_ = (s) => chordToLetter(parseChord(s, F), F);
  assert.equal(let_("F^7"), "Fmaj7");
  assert.equal(let_("Ab7"), "Ab7");
  assert.equal(let_("Db^7"), "Dbmaj7");
  assert.equal(let_("A^7"), "Amaj7");
});

// --- tokenizer preserves structure ----------------------------------

test("tokenizeBody: preserves sections, repeats, endings, time sig", () => {
  const cells = tokenizeBody("*A{T44C^7 |A-7 }N1Z");
  const types = cells.map((c) => c.type);
  assert.deepEqual(types, [
    "sectionOpen", "repeatOpen", "timeSignature",
    "chord", "bar", "chord", "repeatClose", "ending", "end",
  ]);
  assert.equal(cells[0].label, "A");
  assert.deepEqual(cells[2].timeSignature, [4, 4]);
  assert.equal(cells[3].symbol, "C^7");
  assert.equal(cells[7].ending, 1);
});

test("tokenizeBody: handles empty cells, repeat bars, no-chord", () => {
  const cells = tokenizeBody("C^7 XyQKcl x r n");
  const types = cells.map((c) => c.type);
  assert.deepEqual(types, [
    "chord", "empty", "repeatLastBar", "repeatBar", "repeatTwoBars", "chord",
  ]);
  assert.equal(cells[5].noChord, true);
});

test("tokenizeBody: resolves W invisible-slash to previous chord root", () => {
  // "W/C" means: previous chord's root+quality over a C bass.
  const cells = tokenizeBody("A-7 W/C");
  const chords = cells.filter((c) => c.type === "chord");
  assert.equal(chords[0].symbol, "A-7");
  assert.equal(chords[1].symbol, "A-7/C");
});

test("tokenizeBody: ignores size hints and vertical spacers", () => {
  // 's'/'l' size hints and 'Y' spacers carry no content.
  const cells = tokenizeBody("sC^7 lA-7 YY|");
  assert.deepEqual(
    cells.map((c) => c.type),
    ["chord", "chord", "bar"]
  );
  assert.equal(cells[0].symbol, "C^7");
});

// --- harmony model: Song assembly + flags ---------------------------

test("buildSong: assembles a clean 4/4 Song with Roman chords", () => {
  const song = buildSong({
    title: "Test Tune", composer: "Tester X", style: "Medium Swing",
    key: "C", body: SONG1_BODY,
  });
  assert.equal(song.title, "Test Tune");
  assert.deepEqual(song.key, { tonicPitchClass: 0, mode: "major" });
  assert.deepEqual(song.timeSignature, [4, 4]);
  assert.equal(song.supported, true);
  assert.deepEqual(song.flags, []);

  // chords are stored in key-relative Roman form, with raw kept.
  const chords = song.progression.filter((c) => c.type === "chord");
  assert.equal(chords[0].raw, "C^7");
  assert.deepEqual(chords[0].chord, {
    degree: 1, accidental: "", quality: "^7", raw: "C^7",
  });
  // structure preserved: a repeatOpen and an ending exist.
  assert.ok(song.progression.some((c) => c.type === "repeatOpen"));
  assert.ok(song.progression.some((c) => c.type === "ending" && c.ending === 1));
  assert.ok(song.progression.some((c) => c.type === "sectionOpen" && c.label === "B"));
});

test("buildSong: flags unsupported meter rather than crashing", () => {
  const song = buildSong({
    title: "Five Four", composer: "X", style: "Odd",
    key: "C", body: "T54C^7 |A-7 Z",
  });
  assert.equal(song.supported, false);
  assert.ok(song.flags.some((f) => /unsupported meter 5\/4/.test(f)));
  // still produced a progression (no crash).
  assert.ok(song.progression.length > 0);
});

test("buildSong: defaults to 4/4 and flags when body has no time sig", () => {
  const song = buildSong({
    title: "No TS", composer: "X", style: "Y", key: "C",
    body: "C^7 |A-7 Z",
  });
  assert.deepEqual(song.timeSignature, [4, 4]);
  assert.ok(song.flags.some((f) => /no time signature/.test(f)));
});

test("buildSong: 3/4 is supported", () => {
  const song = buildSong({
    title: "Waltz", composer: "X", style: "Jazz Waltz", key: "A-",
    body: "T34A-7 |D7 Z",
  });
  assert.deepEqual(song.timeSignature, [3, 4]);
  assert.equal(song.supported, true);
});

// --- end-to-end through the HTML --------------------------------------

test("parsePlaylistHtml: full pipeline over the embedded sample", () => {
  const playlist = parsePlaylistHtml(SAMPLE_HTML);
  assert.ok(playlist);
  assert.equal(playlist.name, "My Test List");
  assert.equal(playlist.songs.length, 2);

  const [s1, s2] = playlist.songs;
  assert.equal(s1.title, "Test Tune");
  assert.deepEqual(s1.timeSignature, [4, 4]);
  assert.equal(s1.supported, true);

  assert.equal(s2.title, "Minor Waltz");
  assert.deepEqual(s2.key, { tonicPitchClass: 9, mode: "minor" });
  assert.deepEqual(s2.timeSignature, [3, 4]);
  assert.equal(s2.supported, true);

  // Letter render of song 2's first chord (A-7 in A minor → Am7 → i7 roman).
  const firstChord = s2.progression.find((c) => c.type === "chord");
  assert.equal(chordToRoman(firstChord.chord), "i7");
  assert.equal(chordToLetter(firstChord.chord, s2.key), "Am7");
});

test("parsePlaylistPayload: decoded-payload entry point matches HTML path", () => {
  const payload = extractIrealPayload(SAMPLE_HTML);
  const a = parsePlaylistPayload(payload);
  const b = parsePlaylistHtml(SAMPLE_HTML);
  assert.deepEqual(a, b);
});

test("parsePlaylistHtml: returns null when no irealb URL present", () => {
  assert.equal(parsePlaylistHtml("<html>no chart here</html>"), null);
});
