// Electron main process entry point.
//
// Creates the BrowserWindow that hosts GeoSonel's renderer (index.html),
// sets the app identity (name and dock icon), and hosts the IPC handlers
// that back disk-based score persistence (Stage 2 of the migration).
//
// "GeoSonel" is the user-facing name; "GXW" is the internal code name used
// throughout the source tree. All user-visible strings here use GeoSonel.
//
// Storage layout on disk:
//   <Scores folder>/                  default: ~/Documents/GeoSonel Scores
//     <Score name>.gxs/               macOS package; Stage 6 will add Info.plist
//                                     UTI declarations so Finder folds each .gxs
//                                     folder into a single document icon and
//                                     binds double-click back to GeoSonel.
//                                     Until then, .gxs folders show in Finder as
//                                     folders with the suffix visible.
//       scene.json
//       behaviors.js
//       <image file>                  optional, named per the score's imageName
//       .gxw-meta.json                hidden, carries imageName and any other
//                                     per-score metadata that doesn't fit in
//                                     scene.json
//
// App settings (chosen Scores folder location, current open score, etc.) live
// in <userData>/settings.json, so the Scores folder can be moved or relinked
// without losing app-level state.

const { app, BrowserWindow, ipcMain, dialog } = require('electron');
const path = require('node:path');
const fs = require('node:fs');
const fsp = require('node:fs/promises');

const { installMenu, updateMenuState } = require('./electron-menu.js');

// Set the app name early so it appears in the menu bar, the About dialog,
// and the Force Quit listing instead of the default "Electron".
app.setName('GeoSonel');

let mainWindow;

// Tracks whether the renderer has confirmed that the current close
// gesture should proceed. Set to true after the renderer sends
// 'gxw:close-decision' with 'proceed' (either no unsaved changes, or
// the user picked Save or Don't Save). When the next 'close' event
// fires, the handler sees the flag and allows the close to proceed
// without another interception cycle.
let closeConfirmed = false;

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1600,
    height: 1000,
    title: 'GeoSonel',
    show: false,
    webPreferences: {
      preload: path.join(__dirname, 'electron-preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
    },
  });

  mainWindow.loadFile(path.join(__dirname, 'index.html'));

  mainWindow.once('ready-to-show', () => {
    mainWindow.show();
  });

  // Intercept the close gesture when the renderer has reported unsaved
  // changes. The actual dirty signal is the documentEdited state, which
  // mirrors the bundle's dirty flag via the gxw:set-document-edited IPC
  // handler below. If the document is edited and we haven't already
  // received a proceed decision, prevent the close and ask the renderer
  // to show the three-button "Save changes?" dialog. The renderer's
  // gxw:close-decision message brings us back to either close (proceed)
  // or stay (cancel).
  mainWindow.on('close', (event) => {
    if (closeConfirmed) return;
    if (!mainWindow.isDocumentEdited()) return;
    event.preventDefault();
    mainWindow.webContents.send('gxw:close-requested');
  });
}

// Replace the default Electron dock icon with the GeoSonel icon if it exists.
// The PNG is generated by scripts/build-icon.sh from assets/icon.svg.
function applyDockIcon() {
  if (process.platform !== 'darwin') return;
  const iconPath = path.join(__dirname, 'assets', 'icon.png');
  if (fs.existsSync(iconPath)) {
    app.dock.setIcon(iconPath);
  }
}

// --- Storage paths and settings ---

const SETTINGS_FILENAME = 'settings.json';
const SCORE_META_FILENAME = '.gxw-meta.json';

// Score folders on disk carry a .gxs extension so they read as
// macOS packages — Stage 6 packaging will bind .gxs to GeoSonel
// via Info.plist UTI declarations and Finder will then fold each
// .gxs folder into a single document icon. The renderer continues
// to refer to scores by extensionless display name; the helpers
// below translate between the renderer's name and the on-disk
// folder name. Keeping the translation isolated here (rather than
// teaching the renderer about .gxs) is the explicit shape for
// Stage 3 commit 1: every score-folder path computed in this file
// goes through scoreFolderName, and every name parsed back out of
// a directory listing goes through scoreNameFromFolderName.
const SCORE_FOLDER_EXTENSION = '.gxs';

function scoreFolderName(name) {
  return name + SCORE_FOLDER_EXTENSION;
}

function scoreNameFromFolderName(folderName) {
  if (!folderName.endsWith(SCORE_FOLDER_EXTENSION)) return null;
  return folderName.slice(0, -SCORE_FOLDER_EXTENSION.length);
}

function getSettingsPath() {
  return path.join(app.getPath('userData'), SETTINGS_FILENAME);
}

async function readSettings() {
  try {
    const text = await fsp.readFile(getSettingsPath(), 'utf8');
    return JSON.parse(text);
  } catch (err) {
    if (err.code === 'ENOENT') return {};
    throw err;
  }
}

async function writeSettings(settings) {
  await fsp.mkdir(path.dirname(getSettingsPath()), { recursive: true });
  await fsp.writeFile(
    getSettingsPath(),
    JSON.stringify(settings, null, 2),
    'utf8'
  );
}

async function getScoresFolder() {
  const settings = await readSettings();
  if (typeof settings.scoresFolder === 'string' && settings.scoresFolder.length > 0) {
    return settings.scoresFolder;
  }
  return path.join(app.getPath('home'), 'Documents', 'GeoSonel Scores');
}

async function ensureScoresFolder() {
  const folder = await getScoresFolder();
  await fsp.mkdir(folder, { recursive: true });
  return folder;
}

// --- MIME type inference ---

const TEXT_MIME_PREFIXES = ['text/'];
const TEXT_MIME_EXACT = new Set([
  'application/json',
  'application/javascript',
  'application/xml',
]);

function getMimeType(filename) {
  const ext = path.extname(filename).toLowerCase();
  switch (ext) {
    case '.json': return 'application/json';
    case '.js':   return 'application/javascript';
    case '.txt':  return 'text/plain';
    case '.html': return 'text/html';
    case '.css':  return 'text/css';
    case '.md':   return 'text/markdown';
    case '.png':  return 'image/png';
    case '.jpg':  return 'image/jpeg';
    case '.jpeg': return 'image/jpeg';
    case '.gif':  return 'image/gif';
    case '.webp': return 'image/webp';
    case '.svg':  return 'image/svg+xml';
    default:      return 'application/octet-stream';
  }
}

function isTextMime(mimeType) {
  if (TEXT_MIME_EXACT.has(mimeType)) return true;
  for (const prefix of TEXT_MIME_PREFIXES) {
    if (mimeType.startsWith(prefix)) return true;
  }
  return false;
}

// --- Score record IO ---
//
// A score record (matching the ScoreRecord type in src/storage.js) has:
//   { name, files: { [path]: { mimeType, content } }, imageName, updatedAt }
// Text file content is a string; binary content is an ArrayBuffer that
// crosses IPC via Electron's structured-clone serialisation.

async function pathExists(p) {
  try {
    await fsp.access(p);
    return true;
  } catch (err) {
    if (err.code === 'ENOENT') return false;
    throw err;
  }
}

// Read a score record from an arbitrary folder. Used by
// readScoreRecord (for live scores) and loadBackupRecord (for
// backup slot folders). The record's `name` field is set
// from the second argument so backup records carry the
// original score name rather than the slot folder's numeric
// name. The mtime returned in updatedAt is the source
// folder's own mtime, which for backup slots reflects the
// time the rotation copied that slot's contents into place.
async function readRecordFromFolder(folder, name) {
  let stat;
  try {
    stat = await fsp.stat(folder);
  } catch (err) {
    if (err.code === 'ENOENT') return null;
    throw err;
  }
  if (!stat.isDirectory()) return null;

  // Read the metadata sidecar, if present.
  let imageName = null;
  try {
    const metaText = await fsp.readFile(
      path.join(folder, SCORE_META_FILENAME),
      'utf8'
    );
    const meta = JSON.parse(metaText);
    if (typeof meta.imageName === 'string' || meta.imageName === null) {
      imageName = meta.imageName;
    }
  } catch (err) {
    if (err.code !== 'ENOENT') {
      console.warn('GXW: failed to read score metadata for', name, err);
    }
  }

  // Read every file in the folder except the metadata sidecar
  // and the .backups subfolder.
  const entries = await fsp.readdir(folder, { withFileTypes: true });
  const files = {};
  for (const entry of entries) {
    if (!entry.isFile()) continue;
    if (entry.name === SCORE_META_FILENAME) continue;
    if (entry.name === '.DS_Store') continue;

    const filePath = path.join(folder, entry.name);
    const buffer = await fsp.readFile(filePath);
    const mimeType = getMimeType(entry.name);

    if (isTextMime(mimeType)) {
      files[entry.name] = { mimeType, content: buffer.toString('utf8') };
    } else {
      // Send as ArrayBuffer; Electron's IPC handles the structured clone.
      const ab = buffer.buffer.slice(
        buffer.byteOffset,
        buffer.byteOffset + buffer.byteLength
      );
      files[entry.name] = { mimeType, content: ab };
    }
  }

  return {
    name,
    files,
    imageName,
    updatedAt: stat.mtimeMs,
  };
}

async function readScoreRecord(scorePath) {
  return await readRecordFromFolder(scorePath, scoreNameFromPath(scorePath));
}

function scoreNameFromPath(scorePath) {
  const base = path.basename(scorePath);
  return scoreNameFromFolderName(base) ?? base;
}

async function writeScoreRecord(scorePath, record) {
  // The renderer is the source of truth for where the score
  // lives, so the path is used verbatim rather than being
  // recomputed from record.name + the configured Scores
  // folder. ensureScoresFolder is still called to make sure
  // the parent directory exists for the common case where
  // the score is being saved into the configured Scores
  // folder for the first time; for paths outside it (the
  // commit-3 anywhere-save case), the user picked the
  // directory via Save panel and it already exists.
  await ensureScoresFolder();
  await fsp.mkdir(scorePath, { recursive: true });
  const scoreFolder = scorePath;

  // Track which files should remain in the folder after this save.
  const keepFiles = new Set(Object.keys(record.files));
  keepFiles.add(SCORE_META_FILENAME);

  // Write the metadata sidecar.
  const meta = { imageName: record.imageName ?? null };
  await fsp.writeFile(
    path.join(scoreFolder, SCORE_META_FILENAME),
    JSON.stringify(meta, null, 2),
    'utf8'
  );

  // Delete files in the folder that are no longer in the record (e.g. an
  // image that was removed). Don't touch the metadata sidecar or .DS_Store.
  const existing = await fsp.readdir(scoreFolder, { withFileTypes: true });
  for (const entry of existing) {
    if (!entry.isFile()) continue;
    if (keepFiles.has(entry.name)) continue;
    if (entry.name === '.DS_Store') continue;
    await fsp.unlink(path.join(scoreFolder, entry.name));
  }

  // Write each file from the record.
  for (const [filename, file] of Object.entries(record.files)) {
    const filePath = path.join(scoreFolder, filename);
    if (typeof file.content === 'string') {
      await fsp.writeFile(filePath, file.content, 'utf8');
    } else {
      // ArrayBuffer arriving from the renderer.
      const buffer = Buffer.from(file.content);
      await fsp.writeFile(filePath, buffer);
    }
  }
}

async function deleteScoreRecord(scorePath) {
  await fsp.rm(scorePath, { recursive: true, force: true });
}

// Rename a score on disk by renaming its folder in place. The
// folder rename is one syscall and atomic on the same volume,
// which means the .backups subfolder follows the score to its
// new location with no extra plumbing — contrast the older
// path of save-under-new-name plus delete-old-name, which lost
// the .backups history.
//
// The renderer's promptForUniqueName already guarantees the
// destination doesn't exist, so a collision here would mean
// the caller bypassed that guard or two callers raced. Throw
// rather than silently overwriting; the in-app message area
// surfaces the error to the user.
async function renameScoreRecord(oldPath, newPath) {
  if (oldPath === newPath) return;
  if (!await pathExists(oldPath)) {
    // Nothing to rename on disk — e.g. a brand-new bundle
    // that hasn't been saved yet. The renderer's follow-up
    // save under the new path will create the folder.
    return;
  }
  if (await pathExists(newPath)) {
    throw new Error(
      `Cannot rename to "${newPath}": a score with that name already exists.`
    );
  }
  // Make sure the destination's parent directory exists
  // before the rename. For commit-2 paths this is always the
  // configured Scores folder (already ensured elsewhere),
  // but the explicit mkdir keeps the IPC robust for the
  // commit-3 anywhere-save case where the parent could be
  // any directory.
  await fsp.mkdir(path.dirname(newPath), { recursive: true });
  await fsp.rename(oldPath, newPath);
}

async function listScoreFolders() {
  const scoresFolder = await ensureScoresFolder();
  const entries = await fsp.readdir(scoresFolder, { withFileTypes: true });
  const results = [];
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    if (entry.name.startsWith('.')) continue;
    const name = scoreNameFromFolderName(entry.name);
    if (name === null) continue;
    const folderPath = path.join(scoresFolder, entry.name);
    const stat = await fsp.stat(folderPath);
    results.push({ path: folderPath, name, updatedAt: stat.mtimeMs });
  }
  results.sort((a, b) => b.updatedAt - a.updatedAt);
  return results;
}

async function loadAllScoreRecords() {
  const list = await listScoreFolders();
  const records = [];
  for (const item of list) {
    const record = await readScoreRecord(item.path);
    if (record !== null) records.push(record);
  }
  return records;
}

// --- Numbered backups ---
//
// Stage 2.5 Phase 3 commit 2. Every save of a score under the
// Electron build copies the pre-save state into a numbered
// slot inside <scoreFolder>/.backups/ before the new content
// is written. Slot 1 is always the most recent backup; the
// rotation shifts each existing slot down by one (1→2,
// 2→3, ...) before the copy, and any slot that would
// exceed maxCount after shifting is deleted instead. Slots
// can have gaps if the user manually deleted one in Finder;
// the rotation tolerates them rather than compacting,
// matching the gap-tolerance design decision in IN_FLIGHT.
//
// The renderer's storage.js calls rotateBackupsBeforeSave
// inside saveScoreRecord just before the write, passing the
// user's numBackupsToKeep preference. A first save (score
// folder doesn't yet exist) is a no-op because there's
// nothing to back up.

const BACKUPS_DIRNAME = '.backups';

async function rotateBackupsBeforeSave(scorePath, maxCount) {
  if (typeof maxCount !== 'number' || maxCount <= 0) return;

  const scoreFolder = scorePath;

  // First save: nothing on disk yet, nothing to back up.
  if (!await pathExists(scoreFolder)) return;

  const backupsFolder = path.join(scoreFolder, BACKUPS_DIRNAME);
  await fsp.mkdir(backupsFolder, { recursive: true });

  // Read existing numbered slot folders. Anything that's not
  // a directory or whose name doesn't parse to a positive
  // integer is ignored (defence against stray files or
  // manual user-added folders).
  const entries = await fsp.readdir(backupsFolder, { withFileTypes: true });
  const existingSlots = [];
  for (const e of entries) {
    if (!e.isDirectory()) continue;
    const n = parseInt(e.name, 10);
    if (!Number.isFinite(n) || String(n) !== e.name || n < 1) continue;
    existingSlots.push(n);
  }
  // Walk from highest slot number down to lowest so renames
  // don't collide.
  existingSlots.sort((a, b) => b - a);
  for (const n of existingSlots) {
    const newN = n + 1;
    const oldPath = path.join(backupsFolder, String(n));
    if (newN > maxCount) {
      // This slot would fall off the end after shifting; drop
      // it instead of renaming.
      await fsp.rm(oldPath, { recursive: true, force: true });
    } else {
      const newPath = path.join(backupsFolder, String(newN));
      await fsp.rename(oldPath, newPath);
    }
  }

  // Copy the score's current files (everything in scoreFolder
  // except the .backups subfolder itself and .DS_Store) into
  // a fresh slot 1.
  const slot1 = path.join(backupsFolder, '1');
  await fsp.mkdir(slot1, { recursive: true });
  const scoreEntries = await fsp.readdir(scoreFolder, { withFileTypes: true });
  for (const e of scoreEntries) {
    if (!e.isFile()) continue;
    if (e.name === '.DS_Store') continue;
    await fsp.copyFile(
      path.join(scoreFolder, e.name),
      path.join(slot1, e.name)
    );
  }
}

async function listBackups(scorePath) {
  const backupsFolder = path.join(scorePath, BACKUPS_DIRNAME);

  if (!await pathExists(backupsFolder)) return [];

  const entries = await fsp.readdir(backupsFolder, { withFileTypes: true });
  const slots = [];
  for (const e of entries) {
    if (!e.isDirectory()) continue;
    const n = parseInt(e.name, 10);
    if (!Number.isFinite(n) || String(n) !== e.name || n < 1) continue;
    const stat = await fsp.stat(path.join(backupsFolder, e.name));
    slots.push({ slotNumber: n, mtimeMs: stat.mtimeMs });
  }
  // Slot 1 is the most recent backup; sort ascending so the
  // submenu naturally lists newest first.
  slots.sort((a, b) => a.slotNumber - b.slotNumber);
  return slots;
}

async function loadBackupRecord(scorePath, slotNumber) {
  const slotFolder = path.join(
    scorePath,
    BACKUPS_DIRNAME,
    String(slotNumber)
  );
  // Pass the score's display name (the path's stem) so the
  // record's `name` field round-trips as the live score
  // name. When the renderer reverts to this backup it saves
  // under the original path, which is what the user expects.
  const scoreName = scoreNameFromPath(scorePath);
  return await readRecordFromFolder(slotFolder, scoreName);
}

// --- One-time migration: rename pre-.gxs score folders ---
//
// Before Stage 3 every score lived as a plain folder under the
// Scores folder; commit 1 of Stage 3 introduces the .gxs suffix.
// Existing installs need their score folders renamed so the
// post-commit disk backend, which only recognises .gxs folders,
// can see them. This migration runs on every app launch and
// renames each non-hidden, non-.gxs folder under the Scores folder
// to have a .gxs suffix — but only if the folder contains a
// scene.json file (so it actually is a score). Plain folders the
// user keeps in the Scores folder for other purposes (archives,
// notes, anything else) are left alone, distinguished by the
// absence of scene.json.
//
// Safe to run on every launch: idempotent because folders that
// already end in .gxs are skipped. A folder whose .gxs counterpart
// already exists is logged and skipped rather than overwritten, so
// a conflicting state has to be resolved by the user rather than
// being papered over.
async function migrateScoresFolderToGxsExtension() {
  let folder;
  try {
    folder = await getScoresFolder();
    if (!await pathExists(folder)) return;
  } catch (err) {
    console.warn('GXW: .gxs migration skipped, could not resolve Scores folder:', err);
    return;
  }

  let entries;
  try {
    entries = await fsp.readdir(folder, { withFileTypes: true });
  } catch (err) {
    console.warn('GXW: .gxs migration skipped, could not read Scores folder:', err);
    return;
  }

  let renamed = 0;
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    if (entry.name.startsWith('.')) continue;
    if (entry.name.endsWith(SCORE_FOLDER_EXTENSION)) continue;

    // Score heuristic: contains a scene.json file. Folders
    // without scene.json are unrelated content the user has
    // chosen to keep here and stay untouched.
    const sceneJsonPath = path.join(folder, entry.name, 'scene.json');
    if (!await pathExists(sceneJsonPath)) continue;

    const newFolderName = entry.name + SCORE_FOLDER_EXTENSION;
    const newPath = path.join(folder, newFolderName);
    if (await pathExists(newPath)) {
      console.warn(
        `GXW: .gxs migration skipping "${entry.name}" — "${newFolderName}" already exists.`
      );
      continue;
    }

    try {
      await fsp.rename(path.join(folder, entry.name), newPath);
      renamed++;
    } catch (err) {
      console.warn(`GXW: .gxs migration failed for "${entry.name}":`, err);
    }
  }

  if (renamed > 0) {
    console.log(`GXW: migrated ${renamed} score folder(s) to .gxs extension.`);
  }
}

// --- IPC handler registration ---

function registerStorageHandlers() {
  ipcMain.handle('gxw:list-scores', async () => {
    return await listScoreFolders();
  });

  ipcMain.handle('gxw:load-score-record', async (_event, scorePath) => {
    return await readScoreRecord(scorePath);
  });

  ipcMain.handle('gxw:save-score-record', async (_event, scorePath, record) => {
    await writeScoreRecord(scorePath, record);
  });

  ipcMain.handle('gxw:delete-score-record', async (_event, scorePath) => {
    await deleteScoreRecord(scorePath);
  });

  ipcMain.handle('gxw:rename-score-record', async (_event, oldPath, newPath) => {
    await renameScoreRecord(oldPath, newPath);
  });

  ipcMain.handle('gxw:load-all-score-records', async () => {
    return await loadAllScoreRecords();
  });

  ipcMain.handle('gxw:get-setting', async (_event, key) => {
    const settings = await readSettings();
    return settings[key];
  });

  ipcMain.handle('gxw:set-setting', async (_event, key, value) => {
    const settings = await readSettings();
    settings[key] = value;
    await writeSettings(settings);
  });

  ipcMain.handle('gxw:get-scores-folder', async () => {
    return await getScoresFolder();
  });

  // --- Numbered backups (Stage 2.5 Phase 3 commit 2) ---

  ipcMain.handle('gxw:rotate-backups-before-save', async (_event, scorePath, maxCount) => {
    await rotateBackupsBeforeSave(scorePath, maxCount);
  });

  ipcMain.handle('gxw:list-backups', async (_event, scorePath) => {
    return await listBackups(scorePath);
  });

  ipcMain.handle('gxw:load-backup-record', async (_event, scorePath, slotNumber) => {
    return await loadBackupRecord(scorePath, slotNumber);
  });

  // --- Native dialogs (Stage 3 commit 3a) ---
  //
  // Wrap Electron's dialog.showSaveDialog so the renderer
  // can present the macOS Save panel for Save As. The
  // renderer passes title and defaultPath; we attach the
  // .gxs file filter and return the user's choice as
  // { canceled, filePath }. The dialog's overwrite
  // confirmation runs at the OS level so the renderer
  // doesn't need its own Replace? prompt.
  ipcMain.handle('gxw:show-save-dialog', async (event, options) => {
    const win = BrowserWindow.fromWebContents(event.sender);
    const opts = options ?? {};
    const dialogOpts = {
      title: typeof opts.title === 'string' ? opts.title : 'Save Score',
      filters: [{ name: 'GeoSonel Score', extensions: ['gxs'] }],
    };
    if (typeof opts.defaultPath === 'string') {
      dialogOpts.defaultPath = opts.defaultPath;
    }
    const result = win !== null
      ? await dialog.showSaveDialog(win, dialogOpts)
      : await dialog.showSaveDialog(dialogOpts);
    if (result.canceled || typeof result.filePath !== 'string') {
      return { canceled: true, filePath: null };
    }
    return { canceled: false, filePath: result.filePath };
  });

  // Wrap Electron's dialog.showOpenDialog so the renderer
  // can present the macOS Open panel for Open Score. The
  // dialog runs in openDirectory mode with
  // treatPackageAsDirectory set so .gxs folders read as
  // navigable, selectable folders rather than as packages.
  // Without that property macOS greys out .gxs folders when
  // any file filter is in play — the filter makes the OS
  // treat the extension as a registered document type and a
  // matching folder becomes a non-selectable bundle.
  // Filters are documented as openFile-only and aren't
  // included here for the same reason. The renderer
  // validates the chosen path's .gxs suffix before loading.
  // Returns the single picked path unwrapped from
  // showOpenDialog's filePaths array, in the same
  // { canceled, filePath } shape the Save handler uses.
  ipcMain.handle('gxw:show-open-dialog', async (event, options) => {
    const win = BrowserWindow.fromWebContents(event.sender);
    const opts = options ?? {};
    const dialogOpts = {
      title: typeof opts.title === 'string' ? opts.title : 'Open Score',
      properties: ['openDirectory', 'treatPackageAsDirectory'],
    };
    if (typeof opts.defaultPath === 'string') {
      dialogOpts.defaultPath = opts.defaultPath;
    }
    const result = win !== null
      ? await dialog.showOpenDialog(win, dialogOpts)
      : await dialog.showOpenDialog(dialogOpts);
    if (
      result.canceled ||
      !Array.isArray(result.filePaths) ||
      result.filePaths.length === 0
    ) {
      return { canceled: true, filePath: null };
    }
    return { canceled: false, filePath: result.filePaths[0] };
  });

  // --- Native menu state push (Stage 5 commit 5a) ---
  //
  // The renderer is the source of truth for the state
  // values that drive the native menu's disabled / checked
  // flags (bundle dirty, bundle isUntitled, autoZoom). It
  // pushes a partial state patch through this handler
  // whenever any of those values changes; the menu is
  // rebuilt with the new state and reapplied.
  ipcMain.handle('gxw:menu-state', async (_event, state) => {
    updateMenuState(state ?? {});
  });

  // Window-level IPC for the explicit-save model.
  //
  // setDocumentEdited drives both the dot in the close-button circle
  // (a macOS BrowserWindow convention surfaced via the underlying
  // documentEdited property) and the close-event interceptor's
  // dirty check above. The renderer is the source of truth for
  // dirty state; this handler just forwards it.
  ipcMain.handle('gxw:set-document-edited', async (_event, edited) => {
    if (mainWindow !== undefined && mainWindow !== null) {
      mainWindow.setDocumentEdited(Boolean(edited));
    }
  });

  // Close-decision return path. The renderer sends this after the user
  // picks an option in the three-button "Save changes?" dialog. On
  // 'proceed', set the close-confirmed flag and call close() again; the
  // next 'close' event sees the flag and allows the close. On 'cancel',
  // do nothing — the original close was already prevented.
  ipcMain.on('gxw:close-decision', (_event, decision) => {
    if (decision === 'proceed' && mainWindow !== undefined && mainWindow !== null) {
      closeConfirmed = true;
      mainWindow.close();
    }
  });
}

// --- App lifecycle ---

app.whenReady().then(async () => {
  applyDockIcon();
  registerStorageHandlers();
  await migrateScoresFolderToGxsExtension();
  createWindow();
  installMenu(mainWindow);
});

// On macOS, apps usually stay running when all windows are closed; the user
// explicitly quits via Cmd-Q or the dock menu. On other platforms, closing
// the last window quits the app.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

// On macOS, clicking the dock icon when no windows are open should re-create
// the main window.
app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
