// Electron main process entry point.
// Creates the BrowserWindow that hosts GXW's existing renderer (index.html).
// For Stage 1 of the migration this is the only Electron-specific code;
// the renderer behaves exactly as it does in a browser. Stage 2 will add
// IPC handlers here for disk-based score persistence.

const { app, BrowserWindow } = require('electron');
const path = require('node:path');
const fs = require('node:fs');

// Set the app name early so it appears in the menu bar, the About dialog,
// and the Force Quit listing instead of the default "Electron".
app.setName('GXW');

let mainWindow;

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1600,
    height: 1000,
    title: 'GXW',
    show: false,
    webPreferences: {
      preload: path.join(__dirname, 'electron-preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
    },
  });

  mainWindow.loadFile(path.join(__dirname, 'index.html'));

  mainWindow.once('ready-to-show', () => {
    mainWindow.show();
  });
}

// Replace the default Electron dock icon with the GXW icon if it exists.
// The PNG is generated by scripts/build-icon.sh from assets/icon.svg. There
// will be a brief flash of the default icon at launch before this runs;
// removing that flash requires building a real .app bundle (Stage 6 polish).
function applyDockIcon() {
  if (process.platform !== 'darwin') return;
  const iconPath = path.join(__dirname, 'assets', 'icon.png');
  if (fs.existsSync(iconPath)) {
    app.dock.setIcon(iconPath);
  }
}

app.whenReady().then(() => {
  applyDockIcon();
  createWindow();
});

// On macOS, apps usually stay running when all windows are closed; the user
// explicitly quits via Cmd-Q or the dock menu. On other platforms, closing
// the last window quits the app.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

// On macOS, clicking the dock icon when no windows are open should re-create
// the main window.
app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
