// Electron main process entry point.
//
// Creates the BrowserWindow that hosts GeoSonel's renderer (index.html),
// sets the app identity (name and dock icon), and hosts the IPC handlers
// that back disk-based score persistence (Stage 2 of the migration).
//
// "GeoSonel" is the user-facing name; "GXW" is the internal code name used
// throughout the source tree. All user-visible strings here use GeoSonel.
//
// Storage layout on disk:
//   <Scores folder>/                  default: ~/Documents/GeoSonel Scores
//     <Score name>/
//       scene.json
//       behaviors.js
//       <image file>                  optional, named per the score's imageName
//       .gxw-meta.json                hidden, carries imageName and any other
//                                     per-score metadata that doesn't fit in
//                                     scene.json
//
// App settings (chosen Scores folder location, current open score, etc.) live
// in <userData>/settings.json, so the Scores folder can be moved or relinked
// without losing app-level state.

const { app, BrowserWindow, ipcMain } = require('electron');
const path = require('node:path');
const fs = require('node:fs');
const fsp = require('node:fs/promises');

// Set the app name early so it appears in the menu bar, the About dialog,
// and the Force Quit listing instead of the default "Electron".
app.setName('GeoSonel');

let mainWindow;

// Tracks whether the renderer has confirmed that the current close
// gesture should proceed. Set to true after the renderer sends
// 'gxw:close-decision' with 'proceed' (either no unsaved changes, or
// the user picked Save or Don't Save). When the next 'close' event
// fires, the handler sees the flag and allows the close to proceed
// without another interception cycle.
let closeConfirmed = false;

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1600,
    height: 1000,
    title: 'GeoSonel',
    show: false,
    webPreferences: {
      preload: path.join(__dirname, 'electron-preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
    },
  });

  mainWindow.loadFile(path.join(__dirname, 'index.html'));

  mainWindow.once('ready-to-show', () => {
    mainWindow.show();
  });

  // Intercept the close gesture when the renderer has reported unsaved
  // changes. The actual dirty signal is the documentEdited state, which
  // mirrors the bundle's dirty flag via the gxw:set-document-edited IPC
  // handler below. If the document is edited and we haven't already
  // received a proceed decision, prevent the close and ask the renderer
  // to show the three-button "Save changes?" dialog. The renderer's
  // gxw:close-decision message brings us back to either close (proceed)
  // or stay (cancel).
  mainWindow.on('close', (event) => {
    if (closeConfirmed) return;
    if (!mainWindow.isDocumentEdited()) return;
    event.preventDefault();
    mainWindow.webContents.send('gxw:close-requested');
  });
}

// Replace the default Electron dock icon with the GeoSonel icon if it exists.
// The PNG is generated by scripts/build-icon.sh from assets/icon.svg.
function applyDockIcon() {
  if (process.platform !== 'darwin') return;
  const iconPath = path.join(__dirname, 'assets', 'icon.png');
  if (fs.existsSync(iconPath)) {
    app.dock.setIcon(iconPath);
  }
}

// --- Storage paths and settings ---

const SETTINGS_FILENAME = 'settings.json';
const SCORE_META_FILENAME = '.gxw-meta.json';

function getSettingsPath() {
  return path.join(app.getPath('userData'), SETTINGS_FILENAME);
}

async function readSettings() {
  try {
    const text = await fsp.readFile(getSettingsPath(), 'utf8');
    return JSON.parse(text);
  } catch (err) {
    if (err.code === 'ENOENT') return {};
    throw err;
  }
}

async function writeSettings(settings) {
  await fsp.mkdir(path.dirname(getSettingsPath()), { recursive: true });
  await fsp.writeFile(
    getSettingsPath(),
    JSON.stringify(settings, null, 2),
    'utf8'
  );
}

async function getScoresFolder() {
  const settings = await readSettings();
  if (typeof settings.scoresFolder === 'string' && settings.scoresFolder.length > 0) {
    return settings.scoresFolder;
  }
  return path.join(app.getPath('home'), 'Documents', 'GeoSonel Scores');
}

async function ensureScoresFolder() {
  const folder = await getScoresFolder();
  await fsp.mkdir(folder, { recursive: true });
  return folder;
}

// --- MIME type inference ---

const TEXT_MIME_PREFIXES = ['text/'];
const TEXT_MIME_EXACT = new Set([
  'application/json',
  'application/javascript',
  'application/xml',
]);

function getMimeType(filename) {
  const ext = path.extname(filename).toLowerCase();
  switch (ext) {
    case '.json': return 'application/json';
    case '.js':   return 'application/javascript';
    case '.txt':  return 'text/plain';
    case '.html': return 'text/html';
    case '.css':  return 'text/css';
    case '.md':   return 'text/markdown';
    case '.png':  return 'image/png';
    case '.jpg':  return 'image/jpeg';
    case '.jpeg': return 'image/jpeg';
    case '.gif':  return 'image/gif';
    case '.webp': return 'image/webp';
    case '.svg':  return 'image/svg+xml';
    default:      return 'application/octet-stream';
  }
}

function isTextMime(mimeType) {
  if (TEXT_MIME_EXACT.has(mimeType)) return true;
  for (const prefix of TEXT_MIME_PREFIXES) {
    if (mimeType.startsWith(prefix)) return true;
  }
  return false;
}

// --- Score record IO ---
//
// A score record (matching the ScoreRecord type in src/storage.js) has:
//   { name, files: { [path]: { mimeType, content } }, imageName, updatedAt }
// Text file content is a string; binary content is an ArrayBuffer that
// crosses IPC via Electron's structured-clone serialisation.

async function pathExists(p) {
  try {
    await fsp.access(p);
    return true;
  } catch (err) {
    if (err.code === 'ENOENT') return false;
    throw err;
  }
}

// Read a score record from an arbitrary folder. Used by
// readScoreRecord (for live scores) and loadBackupRecord (for
// backup slot folders). The record's `name` field is set
// from the second argument so backup records carry the
// original score name rather than the slot folder's numeric
// name. The mtime returned in updatedAt is the source
// folder's own mtime, which for backup slots reflects the
// time the rotation copied that slot's contents into place.
async function readRecordFromFolder(folder, name) {
  let stat;
  try {
    stat = await fsp.stat(folder);
  } catch (err) {
    if (err.code === 'ENOENT') return null;
    throw err;
  }
  if (!stat.isDirectory()) return null;

  // Read the metadata sidecar, if present.
  let imageName = null;
  try {
    const metaText = await fsp.readFile(
      path.join(folder, SCORE_META_FILENAME),
      'utf8'
    );
    const meta = JSON.parse(metaText);
    if (typeof meta.imageName === 'string' || meta.imageName === null) {
      imageName = meta.imageName;
    }
  } catch (err) {
    if (err.code !== 'ENOENT') {
      console.warn('GXW: failed to read score metadata for', name, err);
    }
  }

  // Read every file in the folder except the metadata sidecar
  // and the .backups subfolder.
  const entries = await fsp.readdir(folder, { withFileTypes: true });
  const files = {};
  for (const entry of entries) {
    if (!entry.isFile()) continue;
    if (entry.name === SCORE_META_FILENAME) continue;
    if (entry.name === '.DS_Store') continue;

    const filePath = path.join(folder, entry.name);
    const buffer = await fsp.readFile(filePath);
    const mimeType = getMimeType(entry.name);

    if (isTextMime(mimeType)) {
      files[entry.name] = { mimeType, content: buffer.toString('utf8') };
    } else {
      // Send as ArrayBuffer; Electron's IPC handles the structured clone.
      const ab = buffer.buffer.slice(
        buffer.byteOffset,
        buffer.byteOffset + buffer.byteLength
      );
      files[entry.name] = { mimeType, content: ab };
    }
  }

  return {
    name,
    files,
    imageName,
    updatedAt: stat.mtimeMs,
  };
}

async function readScoreRecord(name) {
  const scoresFolder = await getScoresFolder();
  return await readRecordFromFolder(path.join(scoresFolder, name), name);
}

async function writeScoreRecord(record) {
  const scoresFolder = await ensureScoresFolder();
  const scoreFolder = path.join(scoresFolder, record.name);
  await fsp.mkdir(scoreFolder, { recursive: true });

  // Track which files should remain in the folder after this save.
  const keepFiles = new Set(Object.keys(record.files));
  keepFiles.add(SCORE_META_FILENAME);

  // Write the metadata sidecar.
  const meta = { imageName: record.imageName ?? null };
  await fsp.writeFile(
    path.join(scoreFolder, SCORE_META_FILENAME),
    JSON.stringify(meta, null, 2),
    'utf8'
  );

  // Delete files in the folder that are no longer in the record (e.g. an
  // image that was removed). Don't touch the metadata sidecar or .DS_Store.
  const existing = await fsp.readdir(scoreFolder, { withFileTypes: true });
  for (const entry of existing) {
    if (!entry.isFile()) continue;
    if (keepFiles.has(entry.name)) continue;
    if (entry.name === '.DS_Store') continue;
    await fsp.unlink(path.join(scoreFolder, entry.name));
  }

  // Write each file from the record.
  for (const [filename, file] of Object.entries(record.files)) {
    const filePath = path.join(scoreFolder, filename);
    if (typeof file.content === 'string') {
      await fsp.writeFile(filePath, file.content, 'utf8');
    } else {
      // ArrayBuffer arriving from the renderer.
      const buffer = Buffer.from(file.content);
      await fsp.writeFile(filePath, buffer);
    }
  }
}

async function deleteScoreRecord(name) {
  const scoresFolder = await getScoresFolder();
  const scoreFolder = path.join(scoresFolder, name);
  await fsp.rm(scoreFolder, { recursive: true, force: true });
}

async function listScoreFolders() {
  const scoresFolder = await ensureScoresFolder();
  const entries = await fsp.readdir(scoresFolder, { withFileTypes: true });
  const results = [];
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    if (entry.name.startsWith('.')) continue;
    const folderPath = path.join(scoresFolder, entry.name);
    const stat = await fsp.stat(folderPath);
    results.push({ name: entry.name, updatedAt: stat.mtimeMs });
  }
  results.sort((a, b) => b.updatedAt - a.updatedAt);
  return results;
}

async function loadAllScoreRecords() {
  const list = await listScoreFolders();
  const records = [];
  for (const item of list) {
    const record = await readScoreRecord(item.name);
    if (record !== null) records.push(record);
  }
  return records;
}

// --- Numbered backups ---
//
// Stage 2.5 Phase 3 commit 2. Every save of a score under the
// Electron build copies the pre-save state into a numbered
// slot inside <scoreFolder>/.backups/ before the new content
// is written. Slot 1 is always the most recent backup; the
// rotation shifts each existing slot down by one (1→2,
// 2→3, ...) before the copy, and any slot that would
// exceed maxCount after shifting is deleted instead. Slots
// can have gaps if the user manually deleted one in Finder;
// the rotation tolerates them rather than compacting,
// matching the gap-tolerance design decision in IN_FLIGHT.
//
// The renderer's storage.js calls rotateBackupsBeforeSave
// inside saveScoreRecord just before the write, passing the
// user's numBackupsToKeep preference. A first save (score
// folder doesn't yet exist) is a no-op because there's
// nothing to back up.

const BACKUPS_DIRNAME = '.backups';

async function rotateBackupsBeforeSave(scoreName, maxCount) {
  if (typeof maxCount !== 'number' || maxCount <= 0) return;

  const scoresFolder = await getScoresFolder();
  const scoreFolder = path.join(scoresFolder, scoreName);

  // First save: nothing on disk yet, nothing to back up.
  if (!await pathExists(scoreFolder)) return;

  const backupsFolder = path.join(scoreFolder, BACKUPS_DIRNAME);
  await fsp.mkdir(backupsFolder, { recursive: true });

  // Read existing numbered slot folders. Anything that's not
  // a directory or whose name doesn't parse to a positive
  // integer is ignored (defence against stray files or
  // manual user-added folders).
  const entries = await fsp.readdir(backupsFolder, { withFileTypes: true });
  const existingSlots = [];
  for (const e of entries) {
    if (!e.isDirectory()) continue;
    const n = parseInt(e.name, 10);
    if (!Number.isFinite(n) || String(n) !== e.name || n < 1) continue;
    existingSlots.push(n);
  }
  // Walk from highest slot number down to lowest so renames
  // don't collide.
  existingSlots.sort((a, b) => b - a);
  for (const n of existingSlots) {
    const newN = n + 1;
    const oldPath = path.join(backupsFolder, String(n));
    if (newN > maxCount) {
      // This slot would fall off the end after shifting; drop
      // it instead of renaming.
      await fsp.rm(oldPath, { recursive: true, force: true });
    } else {
      const newPath = path.join(backupsFolder, String(newN));
      await fsp.rename(oldPath, newPath);
    }
  }

  // Copy the score's current files (everything in scoreFolder
  // except the .backups subfolder itself and .DS_Store) into
  // a fresh slot 1.
  const slot1 = path.join(backupsFolder, '1');
  await fsp.mkdir(slot1, { recursive: true });
  const scoreEntries = await fsp.readdir(scoreFolder, { withFileTypes: true });
  for (const e of scoreEntries) {
    if (!e.isFile()) continue;
    if (e.name === '.DS_Store') continue;
    await fsp.copyFile(
      path.join(scoreFolder, e.name),
      path.join(slot1, e.name)
    );
  }
}

async function listBackups(scoreName) {
  const scoresFolder = await getScoresFolder();
  const backupsFolder = path.join(scoresFolder, scoreName, BACKUPS_DIRNAME);

  if (!await pathExists(backupsFolder)) return [];

  const entries = await fsp.readdir(backupsFolder, { withFileTypes: true });
  const slots = [];
  for (const e of entries) {
    if (!e.isDirectory()) continue;
    const n = parseInt(e.name, 10);
    if (!Number.isFinite(n) || String(n) !== e.name || n < 1) continue;
    const stat = await fsp.stat(path.join(backupsFolder, e.name));
    slots.push({ slotNumber: n, mtimeMs: stat.mtimeMs });
  }
  // Slot 1 is the most recent backup; sort ascending so the
  // submenu naturally lists newest first.
  slots.sort((a, b) => a.slotNumber - b.slotNumber);
  return slots;
}

async function loadBackupRecord(scoreName, slotNumber) {
  const scoresFolder = await getScoresFolder();
  const slotFolder = path.join(
    scoresFolder,
    scoreName,
    BACKUPS_DIRNAME,
    String(slotNumber)
  );
  // Pass scoreName (not the slot number) so the record's
  // `name` field round-trips as the live score name. When
  // the renderer reverts to this backup it saves under the
  // original score name, which is what the user expects.
  return await readRecordFromFolder(slotFolder, scoreName);
}

// --- IPC handler registration ---

function registerStorageHandlers() {
  ipcMain.handle('gxw:list-scores', async () => {
    return await listScoreFolders();
  });

  ipcMain.handle('gxw:load-score-record', async (_event, name) => {
    return await readScoreRecord(name);
  });

  ipcMain.handle('gxw:save-score-record', async (_event, record) => {
    await writeScoreRecord(record);
  });

  ipcMain.handle('gxw:delete-score-record', async (_event, name) => {
    await deleteScoreRecord(name);
  });

  ipcMain.handle('gxw:load-all-score-records', async () => {
    return await loadAllScoreRecords();
  });

  ipcMain.handle('gxw:get-setting', async (_event, key) => {
    const settings = await readSettings();
    return settings[key];
  });

  ipcMain.handle('gxw:set-setting', async (_event, key, value) => {
    const settings = await readSettings();
    settings[key] = value;
    await writeSettings(settings);
  });

  ipcMain.handle('gxw:get-scores-folder', async () => {
    return await getScoresFolder();
  });

  // --- Numbered backups (Stage 2.5 Phase 3 commit 2) ---

  ipcMain.handle('gxw:rotate-backups-before-save', async (_event, scoreName, maxCount) => {
    await rotateBackupsBeforeSave(scoreName, maxCount);
  });

  ipcMain.handle('gxw:list-backups', async (_event, scoreName) => {
    return await listBackups(scoreName);
  });

  ipcMain.handle('gxw:load-backup-record', async (_event, scoreName, slotNumber) => {
    return await loadBackupRecord(scoreName, slotNumber);
  });

  // Window-level IPC for the explicit-save model.
  //
  // setDocumentEdited drives both the dot in the close-button circle
  // (a macOS BrowserWindow convention surfaced via the underlying
  // documentEdited property) and the close-event interceptor's
  // dirty check above. The renderer is the source of truth for
  // dirty state; this handler just forwards it.
  ipcMain.handle('gxw:set-document-edited', async (_event, edited) => {
    if (mainWindow !== undefined && mainWindow !== null) {
      mainWindow.setDocumentEdited(Boolean(edited));
    }
  });

  // Close-decision return path. The renderer sends this after the user
  // picks an option in the three-button "Save changes?" dialog. On
  // 'proceed', set the close-confirmed flag and call close() again; the
  // next 'close' event sees the flag and allows the close. On 'cancel',
  // do nothing — the original close was already prevented.
  ipcMain.on('gxw:close-decision', (_event, decision) => {
    if (decision === 'proceed' && mainWindow !== undefined && mainWindow !== null) {
      closeConfirmed = true;
      mainWindow.close();
    }
  });
}

// --- App lifecycle ---

app.whenReady().then(() => {
  applyDockIcon();
  registerStorageHandlers();
  createWindow();
});

// On macOS, apps usually stay running when all windows are closed; the user
// explicitly quits via Cmd-Q or the dock menu. On other platforms, closing
// the last window quits the app.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

// On macOS, clicking the dock icon when no windows are open should re-create
// the main window.
app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
