// Merged Strudel + GXW jsdoc data. Concatenates the docs arrays
// from the Strudel-derived vendor file and our own gxw-doc.js so
// the vendored autocomplete.mjs and tooltip.mjs see a single
// uniform list of completion entries.
//
// Strudel entries (the bulk of the list) come from
// strudel-doc.js, which is auto-generated by
// scripts/refresh-strudel-doc.sh from a checkout of the Strudel
// monorepo. GXW-specific entries (our own signals, helpers, and
// runtime additions) come from gxw-doc.js, which is hand-edited.
//
// Order: GXW entries come last so that if a name collides between
// Strudel and GXW, the GXW entry wins (later one in the array is
// what autocomplete sees first). This lets us override a Strudel
// entry's documentation if we ever want to, without removing it
// from the Strudel side.
//
// AGPL-3.0-or-later (see repo-root LICENSE).

import strudel from './strudel-doc.js';
import gxw from './gxw-doc.js';

export default {
    docs: [...strudel.docs, ...gxw.docs],
};
